---

# A docker compose that uses upstream Camunda docker images and MySQL. This
# enables persistence and is a test setup for the Kubernetes layout.

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./mysql/:/docker-entrypoint-initdb.d"

  camunda:
    image: camunda/camunda-bpm-platform:7.11.0
    environment:
      - DB_DRIVER=com.mysql.jdbc.Driver
      - DB_URL=jdbc:mysql://db:3306/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=db:3306
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  mysql_data:
