server.port: 8080
spring:
    application:
        name: gemeente-utrecht-camunda-process-platform
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by gradle when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jersey:
        application-path: /api/camunda-rest

camunda:
    bpm:
        history-level: NONE
        process-engine-name: gemeente-utrecht-camunda-process-platform
        authorization:
            enabled: false
            enabled-for-custom-code: false
            tenant-check-enabled: false
        default-serialization-format: "application/json"
jwt:
    token:
        zaak: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImNsaWVudF9pZGVudGlmaWVyIjoicml0ZW5zZSJ9.eyJpc3MiOiJkb2NzLVU1b2FIaGYxQTJUWCIsImlhdCI6MTU0MzI0NjkwNywiemRzIjp7InNjb3BlcyI6WyJ6ZHMuc2NvcGVzLnpha2VuLmxlemVuIiwiemRzLnNjb3Blcy56YWtlbi5hYW5tYWtlbiJdLCJ6YWFrdHlwZXMiOlsiKiJdfX0.FvF76GZjd7XRmfWUSsbJUsDAemISwOhex8MYvfQNv1Y

nlx:
    zaken:
    statussen:

